name: skd
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.7
  youtube_player_iframe: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  tflite_flutter: ^0.11.0
  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.2.0
  animated_background: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/similarity_model.tflite
    - assets/movies_vectors.json
    - assets/animated_logo_for_splash_screen.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/movie_icon.png"
